### PR TITLE
bumping semantic-ui-react to 0.81.1

### PR DESCRIPTION
**Pull request by jefffriesen**
0.81.1 is now on cljsjs

### CODE REVIEW

**Comment by gadfly361** [comment]
@jefffriesen Thanks so much! Just pushed an updated version to clojars.

**Comment by jefffriesen** [comment]
Cool. I'm new to Clojure. How did you push it to Clojars?

**Comment by gadfly361** [comment]
@jefffriesen 

As a prerequisite to push to clojars you need to have an account with https://clojars.org and also have permission to push the repository.

```
lein deploy clojars
;; then follow prompts to enter your username, password, etc.
```

https://github.com/clojars/clojars-web/wiki/Pushing


--- 

If you want to test your project out locally before pushing to clojars, you can run `lein install` and this will install to your ~/.m2 directory (which is also the place that lein will download your clojar dependencies ... so be sure to clear this before running `lein deploy clojars` on your project ... otherwise after you deploy, you wont actually download it from clojars since you already have a local version from doing `lein install`).

**Comment by jefffriesen** [comment]
@gadfly361 Thanks so much for the info. And thanks for this repo!

**Pull request merged**
